[package]
name = "waybrik"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
toml = "1.0.1"
serde = { version = "1.0.225", features = ["derive"] }


gl = "0.10.0"
clap = { version = "4.5.58", features = ["derive"] }
mlua = { version = "0.11", features = ["lua54", "vendored"] }

[dependencies.sdl2]
version = "0.31.0"
# features = ["bundled", "static-link"]
